# Generated by Django 3.2.3 on 2021-05-23 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss_app', '0002_comment_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'news', 'verbose_name_plural': 'news'},
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
        migrations.AlterModelTable(
            name='news',
            table='news',
        ),
    ]
