# Generated by Django 3.2.3 on 2021-06-05 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss_app', '0004_news_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='data_published',
            new_name='date_published',
        ),
    ]
