# Generated by Django 3.2.3 on 2021-06-05 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss_app', '0005_rename_data_published_news_date_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='date_published',
            new_name='pub_date',
        ),
    ]
